### ISSUE TITLE
OpenAPI Files  Server URLs contain trailing slash

### ISSUE THREAD

**Issue by t-huyeng** [LVGL-SL/mapbender-sl#1]
I have created a [list of all OpenAPI-Files](https://github.com/t-huyeng/geoportal-openapis) which are provided by your Geoportal and I discovered a bug inside of your OpenAPI specifications:

As far as I know in all of the specifications the `Server URL` contains a trailing slash.

Example (https://geoportal.saarland.de/spatial-objects/185/api): 
```
{"openapi":"3.0.1",
.....
"servers":[{"url":"https://geoportal.saarland.de/spatial-objects/185/"}],

......

```

See also: https://meta.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#path-keys-no-trailing-slash and https://spec.openapis.org/oas/v3.0.1.html#server-object

**Comment by t-huyeng** [comment]
@lvgl-pl is this the right repository for this issue? I could not find anything related in the code yet.

**Comment by t-huyeng** [comment]
Wurde scheinbar gefixt. Siehe https://github.com/t-huyeng/geoportal-openapis/pull/13/files#diff-8782c504705f2160a0903651a291e791a671086872a21bf1539b1a9bf6888569.

**Comment by lvgl-pl** [comment]
Entschuldigung, dass ich nicht reagiert habe, sollte nicht unhöflich sein. Bei uns ist ein Mitarbeiter ausgeschieden und ich bin dabei mir Git Kenntnisse anzueignen.

**Comment by t-huyeng** [comment]
So sollte das auch nicht gemeint sein. Danke für den fix!
